github: ["@Chicook,"]
patreon: ["WoldVirtual688,"] ["https://www.patreon.com/posts/metaverso-crypto-112515567?utm_medium=clipboard_copy&utm_source=copyLink&utm_campaign=postshare_creator&utm_content=join_link"]
open_collective: ["chicook," ["https://opencollective.com/chicook"]
custom: ["@juanangellopezdiaz ,"] ["https://www.paypal.com/paypalme/juanangellopezdiaz"]
